### PR TITLE
Update screenshots to match latest App screens

### LINKED ISSUE #148: Update screenshots to match latest Semgrep App UI

### PR DESCRIPTION
**Pull request by pabloest**
This fixes #148

### CODE REVIEW

**Comment by pabloest** [comment]
Previews:

FireShot Capture 077 - Managing CI policy - Semgrep Docs - 127 0 0 1

---

### Another: 

FireShot Capture 080 - CI Integrations - Semgrep Docs - 127 0 0 1

**Comment by chmccreery** [comment]
Hey @pabloest a few other things came up that seem higher priority- do you have time and feel like you have the context to edit the text here as well as screenshots?

**Comment by pabloest** [comment]
I am out today and tomorrow but happy to pick it up when I’m back.

**Comment by chmccreery** [comment]
Ended up with time today!

**Comment by pabloest** [comment]
Thanks, @chmccreery! Your text changes look good to me. 

Could you approve the PR? I’m unable since I opened it.

**Review by chmccreery — APPROVED** [review]

**Comment by chmccreery** [comment]
@pabloest done :)

**Comment by pabloest** [comment]
Thanks, @chmccreery !

**Pull request merged**
