### PR TITLE
added option for scheduling in GitHub actions

### PR DESCRIPTION
**Pull request by s-santillan**
### Security

- [x] Change has no security implications (otherwise, ping the security team)

Closes PD-780

### CODE REVIEW

**Comment by raghavjain3** [comment]
@s-santillan can we make the default example for the cron time be every 2 weeks?

**Comment by s-santillan** [comment]
> 
> 
> @s-santillan can we make the default example for the cron time be every 2 weeks?

@raghavjain3 Will do that :)

**Comment by s-santillan** [comment]
@raghavjain3 Checking first with you, is this acceptable: `30 0 1,15 * *` (Runs at 00:30 every 1st and 15th of the month).

**Comment by raghavjain3** [comment]
> @raghavjain3 Checking first with you, is this acceptable: `30 0 1,15 * *` (Runs at 00:30 every 1st and 15th of the month).

@s-santillan yes that's perfect!

**Review by raghavjain3 — APPROVED** [review]

**Pull request merged**
