### PR TITLE
Typos in python command injection

### PR DESCRIPTION
**Pull request by sebix**
### Security

- [x] Change has no security implications (otherwise, ping the security team)

### CODE REVIEW

**Comment by s-santillan** [comment]
Hi @sebix! Thanks for your additions to the docs. Please [sign the CLA](https://cla-assistant.io/returntocorp/semgrep-docs?pullRequest=356) — it ensures that ownership of the contribution stays with you, while we have the necessary legalities to use your contribution. We'd like to send over some swag as thanks for your contribution, which you can receive by [filling out this form](https://r2c.dev/swag).

**Comment by sebix** [comment]
With these three minor spelling fixes I do not gain any rights on the work.

**Review by s-santillan — APPROVED** [review]

**Comment by s-santillan** [comment]
@sebix Merged! Thanks again :)

**Comment by sebix** [comment]
You're welcome

**Pull request merged**
