### PR TITLE
Make supported languages table taller so viewers don’t have to scroll

### PR DESCRIPTION
**Pull request by pabloest**

### CODE REVIEW

**Comment by dlukeomalley** [comment]
@pabloest @DrewDennison Is there an approach that dynamically scales the iframe height to match the contents? Next time a language is added we'll have to update this again.

**Comment by pabloest** [comment]
AFAIK yes but it involves writing JavaScript that sends messages between iframe and parent windows, then dynamically adjusts the DOM element to reflect the size communicated in the message. 
🍝

**Comment by dlukeomalley** [comment]
This change seems moot with changes I see on /docs:

**Comment by pabloest** [comment]
@dlukeomalley That’s on a different page. One is the index page (overview), the other is the language status page. This PR is for the latter.

**Pull request merged**
