### PR TITLE
Add fail open, fail close mention

### PR DESCRIPTION
**Pull request by adamkvitek**
Resolves: https://linear.app/r2c/issue/MKT-365/document-ci-handling-fail-open-and-fail-closestates

# Thanks for improving Semgrep Docs 😀

### Please ensure

- [x] A subject matter expert (SME) reviews the content
- [x] A technical writer reviews the content or PR
- [x] This change has no security implications or else you have pinged the security team
- [x] Redirects are added if the PR changes page URLs

### CODE REVIEW

**Comment by adamkvitek** [comment]
@daghan is this a specific state which CI somehow displays (in that case it should be `fail-open` or `fail-closed`), or is this a general tech support terminology (in that case it should be just "fail open" and "fail closed")? I tried to search for fail open and fail closed for GitHub Actions, it seems more like terminology used outside of the system itself.

**Comment by daghan** [comment]
@dlukeomalley can you chime in here? 

@adamkvitek We use the nomenclature a lot with our customers. The CI agent doesn't display a specific `fail-open` or `fail-closed` state so it is #2 (a part of general tech support methodology)

**Review by daghan — APPROVED** [review]
Looks great

**Review by s-santillan — APPROVED** [review]
lgtm!

**Pull request merged**
