### PR TITLE
Add release notes for Semgrep v0.78.0

### PR DESCRIPTION
**Pull request by pabloest**
### Security

- [X] Change has no security implications (otherwise, ping the security team)

### CODE REVIEW

**Review by s-santillan — COMMENTED** [review]
This only occurred to me now: do we need an example for "metavariable-comparison now handles metavariables that bind to arbitrary constant expressions"? If this is domain knowledge such that programmers will know what it implies for rule writing, then I think it's okay not to have an example, but if it's is an operator with entirely Semgrep-made mechanics, it might be worth it to have an example? But this comment should not be treated as a blocker if it's a minor thing.

**Comment by pabloest** [comment]
@s-santillan Hmm yeah, the PR cites this example rule: [https://semgrep.dev/s/By6x](https://semgrep.dev/s/By6x) 

@IagoAbal Do you think it would be helpful to link to that rule? And should we update a few words on the [metavariable-comparison docs](https://semgrep.dev/docs/writing-rules/data-flow/constant-propagation/#metavariable-comparison) text to reflect this change?

**Comment by pabloest** [comment]
@IagoAbal Any thoughts on adding that rule?

@s-santillan Do you think we can merge this even without the additional context?

**Comment by s-santillan** [comment]
@pabloest Let's merge it for now and then add the example later on? I'll approve it now.

**Review by s-santillan — APPROVED** [review]

**Comment by pabloest** [comment]
Thanks, @s-santillan!

**Pull request merged**
