### PR TITLE
Add image of github pull request comment

### PR DESCRIPTION
**Pull request by brendongo**

### CODE REVIEW

**Comment by brendongo** [comment]
Screen Shot 2021-02-09 at 1 12 42 PM

**Comment by dlukeomalley** [comment]
Thank you @brendongo. Is there anywhere else this imagery may prove useful, like for discussion of Notifications (CC @chmccreery)?

Is there a sample rule that has improved line-wrapping? I see the newlines in the sample image make the text awkwardly wrap (short term manually edit that comment might help).

**Comment by chmccreery** [comment]
I will probably link to this part of the docs from my docs rather than include the same image twice

**Comment by brendongo** [comment]
Updated image: 
semgrep-pull-request

**Pull request merged**
