### PR TITLE
fix a couple of typos in help/usage

### PR DESCRIPTION
**Pull request by parsiya**
also made a PR for the CLI at
https://github.com/returntocorp/semgrep/pull/7184

# Thanks for improving Semgrep Docs 😀

### Please ensure

- [x] A subject matter expert (SME) reviews the content
- [x] A technical writer reviews the content or PR
- [x] This change has no security implications or else you have pinged the security team
- [x] Redirects are added if the PR changes page URLs

### CODE REVIEW

**Review by adamkvitek — APPROVED** [review]

**Comment by adamkvitek** [comment]
@parsiya great suggestions, thanks a lot! Please can you do the same edits against the source of this text that can be found at https://github.com/returntocorp/semgrep (Maybe TWs should also check our `--help` source code also.)

**Comment by s-santillan** [comment]
@parsiya Feel free to merge anytime :)

**Comment by parsiya** [comment]
Hi @s-santillan, I cannot. Could you please merge it instead of me?

I can only "Comment" and "Close with comment" :)

**Comment by parsiya** [comment]
Apologies for creating more work. Was reading the docs and saw `Filtr`, so I went through the docs and fixed a few more typos.

**Comment by adamkvitek** [comment]
@parsiya thank you, I will merge this PR.

**Pull request merged**
