### PR TITLE
Add an explanation about metavariable matching behavior in pattern-no…

### PR DESCRIPTION
**Pull request by minusworld**
…t\* that addresses https://github.com/returntocorp/semgrep/issues/2305

Closes https://github.com/returntocorp/semgrep/issues/2305

### CODE REVIEW

**Comment by mschwager** [comment]
Hmm, there seems to be all kinds of corner cases with this. E.g.

```yaml
rules:
- id: matching-negation
  message: Matching negation
  severity: ERROR
  languages: [python]
  patterns:
    - pattern: $VAR1 = ...
    - pattern-not-inside: |
        def $FUNC(...):
          ...
          $VAR2 = $VAR1
```

```python
a = 5

def func():
    b = a
    return b
```

```
$ python -m semgrep --config /tmp/test.yaml /tmp/test.py
running 1 rules...
/tmp/test.py
severity:error rule:tmp.matching-negation: Matching negation
1:a = 5
--------------------------------------------------------------------------------
4:    b = a
ran 1 rules on 1 files: 2 findings
```

It looks like it's somehow detecting `b` as `$VAR1` in the second finding:

```json
                    "$VAR1": {
                        "start": {
                            "line": 4,
                            "col": 5,
                            "offset": 23
                        },
                        "end": {
                            "line": 4,
                            "col": 6,
                            "offset": 24
                        },
                        "abstract_content": "b",
                        "unique_id": {
                            "type": "id",
                            "value": "b",
                            "kind": "Local",
                            "sid": 2
                        }
                    }
```

Would it make more sense to disable metavariable matching on negation operators? It's a weird operation because `pattern-not-inside` will be true simply if the metavariables don't match, even if the corresponding `pattern` _is_ inside.

**Comment by aryx** [comment]
I don't think we want to disable metavariable matching on negation. We have examples relying on that.

**Comment by aryx** [comment]
and in your example a = 5 is normal, because it's outside the func (so clearly will satisfy pattern-not-inside).
For b = a, b is never found on the right hand side, so the pattern-not-inside returns a match, but with VAR1 bound to a, never bound to b, hence the match

**Review by aryx — APPROVED** [review]
looks good to me.

**Pull request merged**
