### PR TITLE
writing-rules: Add metavariable-pattern

### PR DESCRIPTION
**Pull request by IagoAbal**

### CODE REVIEW

**Comment by IagoAbal** [comment]
Need to wait for `metavariable-pattern` to be available in production before fixing the links for the embed examples.

**Review by pabloest — APPROVED** [review]
Looks great, @IagoAbal !

**Comment by IagoAbal** [comment]
Thanks @pabloest! Now `metavariable-pattern` works in production Playground, fixed the links, good to go!

**Review by minusworld — APPROVED** [review]
Considering that I wrote the original version of the second example, it was especially impactful to me :D

**Comment by IagoAbal** [comment]
@minusworld I actually rewrote the original rule here https://github.com/returntocorp/semgrep/blob/develop/semgrep-core/tests/OTHER/rules/metavar_pattern_open_redirect.yaml in case it's interesting.

@pabloest I see some checks failing but I don't see how those errors are related to my changes. I prefer not to click "merge" out of caution, please someone do if you know it's fine (or please confirm that the errors are caused by this PR).

**Comment by pabloest** [comment]
@IagoAbal I’m familiar with this error. It’s a false positive and I fixed it in another PR that already merged, but that PR was made after you had opened this PR. So it’s all good and I’ll merge this PR and close it now.

**Pull request merged**
