### PR TITLE
Un-nest sidebar links to simplify nav menu, fixes #68

### LINKED ISSUE #68: Sidebar always thinks I'm in the "Writing rules" section
Screen Shot 2020-12-14 at 15 08 36

After clicking on another sidebar item, it flashes correctly for a second and then resets to highlighting this.

### PR DESCRIPTION
**Pull request by pabloest**
Preview: Screen Shot 2021-02-01 at 4 09 18 PM

Also note [this comment](https://github.com/returntocorp/semgrep-docs/issues/68#issuecomment-771259333) from @chmccreery: 

> “I like it! The sections don't all make sense to me immediately (where would I go for Semgrep Action documentation, for example?), but otherwise I am not bothered by the lower amount of nesting.

cc @underyx and @dlukeomalley

### CODE REVIEW

**Comment by dlukeomalley** [comment]
Tentatively lgtm, though I'd like to simplify the sections if possible. Perhaps Rule Syntax and Pattern Syntax can become "Syntax", Rule Examples and Pattern Examples can become Examples, etc.

**Comment by pabloest** [comment]
Thanks, @dlukeomalley. I am mildly in favor of the simplification, my main concern being overall length (they’re already pretty long). 

In the interest of making progress and not complicating things too much, can we merge this and open a separate issue for the section simplification? A simplification change will require redirects and possibly updating links/labels outside the docs.

**Review by chmccreery — APPROVED** [review]
Agree with @dlukeomalley on simplifying or rethinking which categories go on the left hand toolbar, but also in favor of getting this PR in since it is fixing a bug and that is sort of a separate problem

**Comment by pabloest** [comment]
Moving discussion over to a related PR: https://github.com/returntocorp/semgrep-docs/pull/91

**Pull request merged**
