### PR TITLE
Don't truncate headline and description on generated index cards

### PR DESCRIPTION
**Pull request by pabloest**
# Thanks for improving Semgrep Docs 😀

### Please ensure

- [ ] A subject matter expert (SME) reviews the content
- [ ] A technical writer reviews the content or PR
- [x] This change has no security implications or else you have pinged the security team
- [x] Redirects are added if the PR changes page URLs

### CODE REVIEW

**Comment by pabloest** [comment]
### Preview

Screen Shot 2022-11-09 at 9 21 38 AM

**Comment by adamkvitek** [comment]
Looks great! May I remove the Introduction header from https://semgrep.dev/docs/running-rules/ in this PR? @pabloest 

It causes the following issue.

Screenshot 2022-11-09 at 18 32 38

I am not sure if there is any configuration to skip headers and display only the first paragraph.

**Comment by s-santillan** [comment]
Font is a little small. I can fix in follow up PR.

**Review by adamkvitek — APPROVED** [review]
Looks great, I rather removed the Introduction header mentioned in https://github.com/returntocorp/semgrep-docs/pull/779#issuecomment-1309102554

**Comment by pabloest** [comment]
Super, thanks @adamkvitek and @s-santillan !

**Pull request merged**
