### PR TITLE
Include 'Data Flow' docs

### PR DESCRIPTION
**Pull request by mschwager**

### CODE REVIEW

**Comment by ievans** [comment]
thanks for getting this started Matt. At a minimum i think we should specify intraprocedural, with some flow-sensitivity and explain those terms.

@IagoAbal is already working on docs separately?

**Comment by mschwager** [comment]
> @IagoAbal is already working on docs separately?

Cool, I'm happy to let @IagoAbal tackle this since he'll definitely know more than I do :+1:

**Comment by IagoAbal** [comment]
I haven't yet started but it's my intention to write something by the end of this week. You can refine and merge this PR and I can take it from there if you want.

**Comment by dlukeomalley** [comment]
@mschwager @IagoAbal Any updates and/or can we merge this PR? Thank yoU!

**Comment by ievans** [comment]
closed in favor of https://github.com/returntocorp/semgrep-docs/pull/83

**Pull request closed without merging**
