### PR TITLE
Create "supported-languages" from lang.json

### PR DESCRIPTION
**Pull request by nbrahms**
This should reduce frequency of issues with discrepancies between
lang.json and this page.

# Thanks for improving Semgrep Docs 😀

### Please ensure

- [ ] A subject matter expert (SME) reviews the content
- [ ] A technical writer reviews the content or PR
- [ ] This change has no security implications or else you have pinged the security team
- [ ] Redirects are added if the PR changes page URLs

### CODE REVIEW

**Review by adamkvitek — COMMENTED** [review]
@nbrahms thank you for this update!

We need to propagate the table into two files later (index.md and supported-languages.md), would it be possible to propagate the automated text to [this module in this prepared branch](https://github.com/returntocorp/semgrep-docs/pull/613/files#diff-0b300ba5db33f64af2d76c81f06ea0e24a8db7f7c8b95ed8261fa4b8fbd1154bR1-R25) (and should we merge it first)? Just so we can use it as an import consistently in the future and add this table to more pages (without the need to edit the source code of the script).

When I try to build the docs from this branch locally with `yarn start`, I am getting:

```
yarn run v1.22.19
$ bash run-build-scripts && docusaurus start
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26659  100 26659    0     0   271k      0 --:--:-- --:--:-- --:--:--  302k
Installing dependencies from Pipfile.lock (71414a)...
  :snake:   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
Traceback (most recent call last):
  File "/Users/adamkvitek/Documents/GitHub/semgrep-docs/create-supported-languages.py", line 22, in <module>
    with (Path(__file__).parent / "src" / "semgrep-langs" / "lang.json").open() as fd:
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1252, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/local/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1120, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/adamkvitek/Documents/GitHub/semgrep-docs/src/semgrep-langs/lang.json'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

(Is something wrong on my side? Running the build in pipenv made the same results. I mean... lang.json is not in this repository.)

**Comment by nbrahms** [comment]
@adamkvitek I can add docs; you need to `git submodule update --init --recursive`

**Comment by nbrahms** [comment]
Note that this code creates `supported-languages.md` for you. I don't understand how this interacts with `index.md` though?

**Comment by s-santillan** [comment]
@nbrahms Thank you for setting up Jinja! This is the neatest solution I know of to render text from other parts of our ecosystem.

Some context into what Adam is saying: He made a module to render the table (in plain markdown) as a component. 

@adamkvitek We will merge yours first, then Nathan's. Then I can overwrite your table with Nathan's `{{ supported_langs }}`, checking that your table and the generated one are equal.

Btw Nathan, I dunno if you noticed, but we have a build-on-replace script that Matthew kindly made, that overwrites two files in a "brute force" manner (which the Jinja can be used to fix! 😭 🙇 ) These two files will have to be reverted:
```
docs/ignoring-files-folders-code.md
docs/extensions.md
```

let me know if you want me to do that.

**Comment by nbrahms** [comment]
Also @s-santillan @adamkvitek since it seems unlikely this will be merged prior to my departure, some things to consider:

- [ ] You'll need to update filenames in both the build script and in `.gitignore`, when you move to the `.mdx` system
- [ ] You'll need to update https://www.notion.so/r2cdev/How-to-add-or-promote-a-language-6b8cb6e224d54a5eb2a7c4378c5209aa#f4a387636213433697b31592368e16dc after this is merged

**Comment by s-santillan** [comment]
Closing for now (see slack thread for details).

**Pull request closed without merging**
