### PR TITLE
Bence/meta descriptions

### PR DESCRIPTION
**Pull request by underyx**

### CODE REVIEW

**Comment by pabloest** [comment]
@underyx @dlukeomalley should we add a few more custom meta descriptions to this branch and then depend on the mkdocs-meta-descriptions-plugin for the rest?

**Comment by underyx** [comment]
> @underyx @dlukeomalley should we add a few more custom meta descriptions to this branch and then depend on the mkdocs-meta-descriptions-plugin for the rest?

if you think this is an improvement over what we have today, I'd merge and add descriptions in a new PR (today if possible)

**Comment by pabloest** [comment]
@underyx Great. I do and will do.

**Review by pabloest — APPROVED** [review]

**Comment by underyx** [comment]
Awesome, thank you!

**Pull request merged**
