### PR TITLE
update code highlighting in cheat sheets

### PR DESCRIPTION
**Pull request by inkz**
Provide an opportunity to explicitly set the language for a code example, because highlight js not always guesses it right

image

### CODE REVIEW

**Comment by pabloest** [comment]
@inkz Thanks for opening this PR!

Are the code examples supposed to be on one line now? This is what I see:
Screen Shot 2021-06-20 at 8 48 31 PM

**Comment by inkz** [comment]
@pabloest 
well it is supposed to be like this for this version of code, but let me merge it with `main` branch to make it work and mitigate possible conflicts

**Comment by inkz** [comment]
now it has to be multi-line code, properly highlighted :+1:

**Comment by pabloest** [comment]
@inkz Yeah, it looks good now. Thanks!

**Review by pabloest — APPROVED** [review]

**Pull request merged**
