### PR TITLE
Use sass

### PR DESCRIPTION
**Pull request by pabloest**
# Thanks for improving Semgrep Docs 😀

### Please ensure

- [ ] A subject matter expert (SME) reviews the content
- [ ] A technical writer reviews the content or PR
- [x] This change has no security implications or else you have pinged the security team
- [ ] Redirects are added if the PR changes page URLs

### CODE REVIEW

**Comment by pabloest** [comment]
@s-santillan Mind checking that this builds locally for you? I used it to test our staging but rather than discard it, I figured it would be useful to have in main.

**Review by s-santillan — APPROVED** [review]
@pabloest Happy to use scss moving forward, just curious what we're going to use it for? (mixins, variables, proportional font computing...?) Or is this something like unifying app/main marketing website/docs stack (so that other engineers can help us or we can copy scss snippets from them)?

Approved btw! 🚀

**Comment by s-santillan** [comment]
(And yes it works on my end!)

**Comment by pabloest** [comment]
Thanks, @s-santillan. 

Re: using scss, potentially yes to everything you said, but only as needed. I have no vision of “migrating” to scss, but since css works as-is in sass, we can just use sass opportunistically.

**Pull request merged**
