### PR TITLE
Add tabs to getting started with CLI, edit initial header, minor edits

### PR DESCRIPTION
**Pull request by adamkvitek**
# Thanks for improving Semgrep Docs 😀

### Please ensure

- [ ] A subject matter expert (SME) reviews the content
- [x] A technical writer reviews the content or PR
- [x] This change has no security implications or else you have pinged the security team
- [ ] Redirects are added if the PR changes page URLs

### CODE REVIEW

**Comment by pabloest** [comment]
@adamkvitek What's the reasoning behind removing the Linux and WSL references and replacing those with pip? (referring to the new tab labels)

**Comment by adamkvitek** [comment]
@pabloest I was not sure if the WSL label is not too long. Let me know if the following screenshots look better:
Screenshot 2023-01-04 at 17 54 46
Screenshot 2023-01-04 at 17 54 56
Screenshot 2023-01-04 at 17 55 09

**Comment by pabloest** [comment]
> so why specify such information?

The main reason is to specify the operating environments in which one might use Semgrep. macOS, Linux, WSL, and Docker are those, but pip is not. If we move to labeling the package manager instead, then I’d use something like Homebrew, pip, and Docker.

**Comment by adamkvitek** [comment]
Users can use pip install also on their macOS, so maybe:
1. Screenshot 2023-01-04 at 19 49 12
2. Screenshot 2023-01-04 at 19 49 32
3. Screenshot 2023-01-04 at 19 49 48
4. Screenshot 2023-01-04 at 19 50 05

**Comment by pabloest** [comment]
Looks good, @adamkvitek. Thank you!

**Review by pabloest — APPROVED** [review]

**Pull request merged**
