### PR TITLE
update scan dedupe behavior

### PR DESCRIPTION
**Pull request by s-santillan**
# Thanks for improving Semgrep Docs 😀

### Please ensure

- [x] A subject matter expert (SME) reviews the content
~~- [ ] A technical writer reviews the content or PR~~ small-sized PR
- [x] This change has no security implications or else you have pinged the security team

### CODE REVIEW

**Review by chmccreery — COMMENTED** [review]
This isn't really accurate until/unless we change our API. How do you feel about specifying that deduplication happens in the UI but not in the API or waiting until we fix the API to mimic the UI behavior?

**Comment by s-santillan** [comment]
@chmccreery sorry for the late reply - what's the state of the API now? If it's not fixed, I'll just add the caveat so we can merge this ASAP.

**Comment by chmccreery** [comment]
The API now let's you specify "dedup" behavior - by default it does not dedup across branches, but by specifying "dedup = True" you can get the same behavior. I think it's fine to merge this or add a caveat about that.

**Review by chmccreery — APPROVED** [review]

**Comment by s-santillan** [comment]
@chmccreery Thanks. I separated the two and linked to the dedup flag in the Semgrep API docs. Merging :)

**Pull request merged**
