### PR TITLE
Added: autocomplete documentation

### PR DESCRIPTION
**Pull request by ajbt200128**
Documentation for  [corresponding PR](https://github.com/returntocorp/semgrep/pull/4529)

### Security

- [X] Change has no security implications (otherwise, ping the security team)

### CODE REVIEW

**Review by s-santillan — APPROVED** [review]
@ajbt200128 LGTM 👍

**Comment by s-santillan** [comment]
@ajbt200128 Feel free to squash and merge.

**Comment by aryx** [comment]
We can merge once the PR is approved.

**Comment by s-santillan** [comment]
@aryx 0.80.0 changelog indicates autocomplete has been added (https://github.com/returntocorp/semgrep/releases/tag/v0.80.0) Can we merge? 😄

**Comment by aryx** [comment]
Sure!

**Pull request merged**
