### PR TITLE
Sync language support status with index page

### PR DESCRIPTION
**Pull request by connorg**
As a side-effect, this alphabetizes Scala before TS/TSX.

I almost missed Scala support because it was below TypeScript, then found that `index.md` had been updated and this one hadn't.

# Thanks for improving Semgrep Docs 😀

### Please ensure

- [x] A subject matter expert (SME) reviews the content
- [x] A technical writer reviews the content or PR
- [x] This change has no security implications or else you have pinged the security team
- [x] Redirects are added if the PR changes page URLs

### CODE REVIEW

**Review by underyx — APPROVED** [review]
Whoops, thanks a lot!

**Comment by connorg** [comment]
Sorry about the push @underyx! You were too quick. I wanted to attribute this properly to my work email and also add a comment for future maintainers.

**Comment by underyx** [comment]
Sure thing!

**Review by underyx — APPROVED** [review]

**Comment by connorg** [comment]
Hi @underyx, just wanted to let you know that, if you need the CLA, I submitted it for legal review with my employer. (I see the auto-merge is blocked for other reasons, but wanted to mention this before heading out from work for the remainder of the week.)

**Comment by underyx** [comment]
Of course I don't think the CLA makes any sense in this case. But I think if you already submitted it for review, it might be less effort to wait for that approval rather than figuring out what might go wrong if I force-merge this 😬

**Comment by connorg** [comment]
No rush on my side! I did submit it. I would expect to hear back by next
week.

**Review by adamkvitek — APPROVED** [review]

**Comment by connorg** [comment]
[01707f5](https://github.com/returntocorp/semgrep-docs/pull/509/commits/01707f51e4e7fcaa75b65592c5dab034c8061982) brought index.md and status.md back out of sync so I've re-synced them.

CLA is signed now, should be good to go!

**Comment by underyx** [comment]
Thanks so much, especially for taking the time with the CLA even though it can feel like pointless bureaucracy in cases like this! 😶

**Pull request merged**
